version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1
    steps:
      - run: php -v
      - checkout
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            # Find a cache corresponding to this specific composer.lock checksum
            # when this file is changed, this key will fail
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/caching/)
            # (match the most recently generated cache used from any branch)
            - composer-v1-
      - run:
          name: Install
          command: composer install --no-progress --no-interaction --prefer-dist
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: Lint
          command: |
            vendor/bin/parallel-lint --exclude .git --exclude vendor .          
            vendor/bin/phpstan -V
            vendor/bin/phpstan analyse --no-interaction --no-progress
      - run:
          name: Test
          command: |
            ls -la
            echo "no tests to run yet"
